# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Upload Artifact

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: windows-2019
    needs: [ build ]

    steps:
    - name: Upload windows executable
      uses: actions/upload-artifact@v2
      with:
        name: radio_sync-${{ github.job }}
        path: dist/radio_sync.exe
