# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build executeable

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on Windows
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies on Windows
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build windows executable
      run: |
        pyinstaller -F radio_sync.py
  release:
    runs-on: windows-2019
    needs: [ build ]
    if: $${{ github.ref == 'refs/heads/ftm400' }}
    steps:
    - name: Upload windows executable
      uses: actions/upload-artifact@v2
      with:
        name: radio_sync-${{ github.job }}
        path: dist/radio_sync.exe
