
name: Build executeable

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: windows-2019
    if: $${{ github.ref == 'refs/heads/ftm400' }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Use build
      uses: ./.github/workflows/pyinstaller-build.yml
    - name: Upload windows executable
      uses: actions/upload-artifact@v2
      with:
        name: radio_sync-${{ github.job }}
        path: dist/radio_sync.exe